services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: agni_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: agni_db
      POSTGRES_USER: agni_user
      POSTGRES_PASSWORD: agni_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agni_user -d agni_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
